### ISSUE TITLE
Package API details not displayed locally

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.pdffit2#70]
![Screenshot 2024-08-20 at 5 39 30 PM](https://github.com/user-attachments/assets/1ec3c69e-7b0b-4d2c-85cc-955e35c08426)

It appears the API doc details are not shown on my local machine.

How to reproduce:

- Python 3.11 env, installed locally via `pip install -e .`
- Create via `make html`

**Comment by sbillinge** [comment]
thanks for reporting

**Comment by Tieqiong** [comment]
go to conf.py and remove diffpy.pdffit2 in autodoc_mock. Mocking the package itself will not generate anything
